apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.job_name }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: kafka-connector-{{ .Values.job_name }}
  dataFrom: 
  - extract: 
      key: {{ .Values.vault_path }}